-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."coupons" add column "used_count" integer
--  not null default '0';
