-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."merchant_coupons" add column "percent_discount" integer
--  null;
