version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=astro-party
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3309:3306'
    volumes:
      - db:/var/lib/mysql
      - ./seed_data:/docker-entrypoint-initdb.d
volumes:
  db:
    driver: local
