-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."merchant_charges" add column "merchant_customer_id" uuid
--  null;
